### ISSUE TITLE
TODO list 1.0

### ISSUE THREAD

**Issue by arcan1s** [arcan1s/queued#1]
Meta issue about things which need to be implemented before release 1.0. This list may be appended in any time before release.

- [ ] Plugins example
    - [x] email notify plugin
    - [ ] audit plugin
- [ ] Documentation for commands (mans, completions, etc)
- [x] Split ugly `QuadroCore` class
- [ ] Tests
- [ ] Integrations
- [ ] User guide
- [x] Use native cgroups (?)
- [x] Options read policy
- [x] Use database requests inside managers if object wasnt found in memory
- [ ] Task modification support
- [x] Plugin metadata support - license, options, description, author, etc
- [x] Max priority field
- [x] Hide non-users tasks/users
